{
  'printWidth': 70,
  'tabWidth': 2,
  'useTabs': false,
  'semi': true,
  'singleQuote': true,
  'jsxSingleQuote': true,
  'trailingComma': 'none',
  'bracketSpacing': true,
  'jsxBracketSameLine': false,
  'fluid': false,
  'arrowParens': 'always'
}
